### ISSUE TITLE
click event?

### ISSUE THREAD

**Issue by bjarthur** [visjs/vis-graph3d#117]
graph2d has click and doubleclick events from which one can get the x,y position of the mouse.  something similar would be nice for graph3d, whereby one could get the x,y,z coordinates of a dot in cloud, for instance.  this is not documented, but it is possible somehow?  thanks.

**Comment by coldfix** [comment]
graph3d also has an `onclick` event which can be set via the `options` parameter, e.g.:

```
var options = {
    ...
    onclick = point => {console.log(point);},
    ...
};
var graph = new vis.Graph3d(elem, data, options);
```

It is also [documented](https://visjs.github.io/vis-graph3d/docs/graph3d/index.html#Configuration_Options).

**Comment by bjarthur** [comment]
fantastic!  as a new user, i went straight to the events sections of the docs, saw onclick for 2D but not 3D there, and did not think to look under options or elsewhere.  is there a reason for the difference in API?  will give it a try!  thanks.

**Comment by Thomaash** [comment]
There should be an event for this. The way it is now is just weird. Any volunteers?

**Comment by coldfix** [comment]
I can do it. Should I break backward compatibility by replacing the `onclick` option or just add the event in addition?

Btw: I also plan some further changes to let the user pass custom colormaps, e.g. using chroma.js. Where do you stand on breaking backward compatibility when it allows simplifying internals?

**Comment by Thomaash** [comment]
First of all, thanks.

Do just a minor change and deprecate it using some message through `console.warn` when used.
