### ISSUE TITLE
Custom surface colours

### ISSUE THREAD

**Issue by ZackTherrien** [visjs/vis-graph3d#25]
It would be nice to be able to customize the surface colours instead of the default green to red scale.

**Comment by mojoaxel** [comment]
@ZackTherrien What would you recommend?

**Comment by ZackTherrien** [comment]
> @ZackTherrien What would you recommend?

@mojoaxel 
I was thinking of making a PR for this, if that is ok..

**Comment by Thomaash** [comment]
Hi @ZackTherrien,

a PR wouldn't be just okay, it would be awesome. However first we should have a short discussion about the feature, what exactly it should achieve, how it should be configured etc.

**Comment by ZackTherrien** [comment]
Alright! So I was thinking of giving the user the option of modifying the surface colours, so that they can customize the colour range of their surface.

Turning something like: 
![Screen Shot 2019-10-25 at 10 47 57 AM](https://user-images.githubusercontent.com/22176327/67580845-fd255680-f714-11e9-9135-0b6f599e9266.png)

Into:
![Screen Shot 2019-10-25 at 10 48 47 AM](https://user-images.githubusercontent.com/22176327/67580882-0ca49f80-f715-11e9-91bf-c77eadf1410d.png)

As for the configuration, I was thinking of adding the option:
```
surfaceColors: [ HexColorCodeString ]
```

Where the user provides a minimum of 2 `surfaceColors`. The user could specify more colours for a more fine-tuned gradient. (i.e. z-max = RED, z-min: BLUE, but z-avg: PINK).

**Comment by Thomaash** [comment]
One more question here as this isn't clear to me from your explanation: If I specify blue to red gradient `surfaceColors: ["#0000FF", "#FF0000"]` will the color change by hue (blue to cyan to green to yellow to red) or just blend (blue to magenta to red)?

**Comment by ZackTherrien** [comment]
> One more question here as this isn't clear to me from your explanation: If I specify blue to red gradient `surfaceColors: ["#0000FF", "#FF0000"]` will the color change by hue (blue to cyan to green to yellow to red) or just blend (blue to magenta to red)?

It would go by Hue.

**Comment by Thomaash** [comment]
What if someone uses: `surfaceColors: ["#FFFFFF", "#000000"]`? It's not possible to get from one to the other by changing hue.

**Comment by ZackTherrien** [comment]
It would vary over the saturation and value as well.

**Comment by Thomaash** [comment]
Could you maybe provide some example of this? I can't really imagine what you have in mind. Thanks.

**Comment by ZackTherrien** [comment]
> Could you maybe provide some example of this? I can't really imagine what you have in mind. Thanks.

**Comment by ZackTherrien** [comment]
For black to white it would look like:

![Screen Shot 2019-10-25 at 5 19 20 PM](https://user-images.githubusercontent.com/22176327/67605187-9f603100-f74b-11e9-8519-c99b2d2582d4.png)

**Comment by Thomaash** [comment]
Okay, seems intuitive when you have monochromatic only or colors. But I'm still quite lost when it's combined. How would `surfaceColors: ['#000000', '#00FF00', '#FFFFFF']` look? Would it go through red and blue? Would it just be black, green and white? A combination of these two? Something else?

**Comment by ZackTherrien** [comment]
I'm trying to get that working right now. But the gradient would look like:

![Screen Shot 2019-10-28 at 10 10 32 AM](https://user-images.githubusercontent.com/22176327/67685309-3bb44e80-f96b-11e9-857b-b64be024e9fd.png)

**Comment by Thomaash** [comment]
What if the backend supported only blending colors that would make the implementation pretty straight forward. The option input can have hue ranges. These could quite easily be converted to a list of colors to blend that the backend would understand.

#### Color blending (red → purple → blue):
```javascript
const surfaceColors = ["#FF0000", "#0000FF"];
```
This would be used directly.

#### Hue (amber → yellow → green → cyan):
```javascript
const surfaceColors = {
  hue: {
    start: 40,
    end: 180,
    saturation: 50,
    brightness: 100
  }
};
```

This would be converted to:
```javascript
const surfaceColors = [
  "#FFD480",
  "#FFFF80",
  "#D5FF80",
  "#AAFF80",
  "#80FF80",
  "#80FFAA",
  "#80FFD4",
  "#80FFFF"
];
```
and then used.

**Comment by ZackTherrien** [comment]
Yes that sounds reasonable. I will try to implement this.
