### ISSUE TITLE
2 finger touch

### ISSUE THREAD

**Issue by asseldonk** [visjs/vis-graph3d#26]
When I do a 2 finger touch (e.g. pinch zoom) in a graph, the touch event is not released at the end of the touch event: a subsequent single finger touch anywhere else in the browser (e.g. scrolling), leads to a rotation of the graph.

In general: 2 finger touch leads to strange behaviour, the graph is performing weird rotations.

**Comment by Thomaash** [comment]
Hi @asseldonk,

I don't have deep insight into this library but it doesn't seem like there is any support for touch input. It would probably be better to close this and open a new feature request issue for touch support.

**Comment by asseldonk** [comment]
I've gone a bit through the code and I saw a lot of event handlers for touch events. So I though vis.js would support touch devices.
Nevertheless, errors on mobile devices are not good. So if touch is not supported, touch events should not produce any errors.

**Comment by Thomaash** [comment]
And can I ask where did you find these events?

**Comment by asseldonk** [comment]
e.g. 
- [Graph3d.js#L512](https://github.com/visjs/vis-graph3d/blob/master/lib/graph3d/Graph3d.js#L512)
- [Graph3d.js#L2193](https://github.com/visjs/vis-graph3d/blob/master/lib/graph3d/Graph3d.js#L2193)
- [Graph3d.js#L2209](https://github.com/visjs/vis-graph3d/blob/master/lib/graph3d/Graph3d.js#L2209)

**Comment by Thomaash** [comment]
Hmm, I somehow missed these.

**Comment by mojoaxel** [comment]
Pinch zoom is not implemented. This is probably not that hard to do!
