### ISSUE TITLE
display multiple datasets in different styles simultaneously

### ISSUE THREAD

**Issue by wizzard0** [visjs/vis-graph3d#27]
Graph3d is great, however it seems that it displays only 1 dataset at a time.

It would be great to be able to display 2 datasets simultaneously to compare. Currently it's kinda possible with points, but I want to display points and lines over the surface.

If it's hard to do Z-sorting/Z-buffering to do proper intersection, then just drawing "layers" in order would also be helpful. Currently this can be mimicked by drawing many graphs one over another, but this kills the ability to interact with data points other than the chart on top.

**Comment by wizzard0** [comment]
re: stale: it's Christmas! I understand the delay, but not auto-closing -_-

**Comment by mojoaxel** [comment]
@wizzard0 Feel free to provide a pull-request for this feature-request! 
So far nobody except you seem to be interested in this :-|

**Comment by coldfix** [comment]
I'm interested in having this as well. It seems relatively easy to accomplish (at least for my use case of plotting dot-line on top of a surface plot). However, providing a good API to do this will be challenging.

My quick and dirty hack is to let each point specify its own plot style and set the corresponding drawing method per point. I also needed some changes to `DataGroup.initDataAsMatrix` to make it ignore the non-surface points, but that's more or less it, the sorting still works automatically.

Thinking about a cleaner API.... There are several approaches.

One option is to refactor the current Graph3d into multiple components e.g. Axes3d and Graph3d where Axes3d can be called with multiple Graph3d objects and is responsible for drawing axes, colorbar, etc.

Or one could patch Graph3d/DataGroup to accept a list of datasets (or dataset of datasets) during construction. graph style for each dataset could be passed in by allowing Graph3d's `options.style` to receive lists, or along with the DataSet.

Maybe the least intrusive option might be a variant of my above hack, but let points have a `graphID` to set the index into the `options.style` list.
