### ISSUE TITLE
Playground's example is broken

### ISSUE THREAD

**Issue by kekbait** [visjs/vis-graph3d#37]
**Describe the bug**
https://visjs.github.io/vis-graph3d/examples/graph3d/playground/index.html doesn't work as attended.

**To Reproduce**
1. Go to https://visjs.github.io/vis-graph3d/examples/graph3d/playground/index.html
2. Click on 'Draw graph'

**Expected behavior**
The graph should render.

**Versions:**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 78.0.3904.108

Thanks a lot for you great work btw !

**Comment by Thomaash** [comment]
Thanks for pointing this out. A fix is awaiting review.
