### ISSUE TITLE
Custom surface axis colours

### ISSUE THREAD

**Issue by ZackTherrien** [visjs/vis-graph3d#43]
Let users specify the colours for each of the 3 axis in 3D graph.

I was thinking adding a new option:
```
axisColors: {
  x: color,
  y: color,
  z: color,
}
```

If this option is specified, then `axisColor` will be `null`.

**Comment by mojoaxel** [comment]
Why not! Go for it!

**Comment by tomeroto** [comment]
not working, how to change label color of axis? and also lines of grid?

**Comment by Thomaash** [comment]
This is just a feature request. It has never been implemented.
