### ISSUE TITLE
Possible to do custom X/Y/Z interval labels?

### ISSUE THREAD

**Issue by JamesWuDeveloper** [visjs/vis-graph3d#44]
This is definitely a low priority (or even only really useful for "fringe cases") but is there a way to do custom X/Y/Z interval labels? 

For example, rather than 0, 1, 2, 3, you replace the numbers with colors/clothing/countries? I've attached an image below:

![CustomXYZLabels](https://user-images.githubusercontent.com/59004488/71055838-29a49e80-21ab-11ea-99d7-548fa071a04a.png)

The example is I code my data as [1,2,4] and it plots fine, but the numbers on the actual graph show:

[USA, Pants, Pink]

This is to indicate Pink Pants made in USA, for example. Was hoping there may be a way to do this on the graph front end.

**Comment by Thomaash** [comment]
Hi @JamesWuDeveloper,

do you mean something like https://visjs.github.io/vis-graph3d/examples/graph3d/12_custom_labels.html?
