### ISSUE TITLE
Unable to import VisGraph into a Vue project since VisGraph version 5.9.0 

### ISSUE THREAD

**Issue by darrenchang** [visjs/vis-graph3d#469]
**Describe the bug**
Hi, I was able to import the module using `import VisGraph from 'vis-graph3d'` in VisGraph version 5.3.0 - 5.8.0, but unable to import the module anymore since version 5.9.0. I'm importing the module into a vue-cli project.

**To Reproduce**
Steps to reproduce the behavior (version 5.8.0 works):
1. Install vue-cli. `sudo npm install -g @vue/cli`
2. Create a new vue project `vue create graph3d-5.8.0`
3. Install vis-graph3d@5.8.0 in the vue project. `cd graph3d-5.8.0; npm i vis-graph3d@5.8.0`
4. Inside the project folder, edit the file App.vue to the following.
```
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import VisGraph from 'vis-graph3d';

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  mounted() {
    console.log("VisGraph", VisGraph)
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
5. Start the project using `npm run serve`.
6. Open the project URL. Usually localhost:8080. Open console in the browser, and you should see the console prints `VisGraph [Object]`. If it prints [Object], it means the module is imported successfully. 

Steps to reproduce the behavior (version 5.9.0 doesn't work):
1. Repeat the above steps, but change version from 5.8.0 to 5.9.0.
2. VisGraph3d@5.9.0 seems to require vis-data. `npm install vis-data`.
2. Check the browser's console again. It should display `VisGraph undefined`, because the module is not imported correctly.

**Expected behavior**
I want to be able to import both VisGraph3d version 5.8.0 and 5.9.0 using `import VisGraph from 'vis-graph3d'`.

**Versions:**
 - OS: Ubuntu 20.10
 - Browser: Google Chrome 
 - Version: VisGraph version 5.9.0 and above have this issue.
 - npm version: 6.14.10
 - nodejs version: v12.18.2
 - @vue/cli version: 4.5.9

**Comment by Thomaash** [comment]
Hi @darrenchang,

does `import { Graph3d } from "vis-graph3d/standalone"` work?

**Comment by darrenchang** [comment]
> Hi @darrenchang,
> 
> does `import { Graph3d } from "vis-graph3d/standalone"` work?

Hi. It works now. Thank you for the help.
