### ISSUE TITLE
[Bug] Failed deployment?

### ISSUE THREAD

**Issue by ZackTherrien** [visjs/vis-graph3d#53]
I think the deployment is broken.
When loading any of the examples [ex](https://visjs.github.io/vis-graph3d/examples/graph3d/01_basics.html), the console says 

<img width="486" alt="Screen Shot 2020-01-03 at 11 15 34 AM" src="https://user-images.githubusercontent.com/22176327/71734654-61058300-2e1a-11ea-9468-6ab5a140ab78.png">

**Comment by Thomaash** [comment]
Hi @ZackTherrien,

thanks for reporting this. It should be fixed now. Can you check if it works for you and close this issue if so, please?

**Comment by ZackTherrien** [comment]
Looks great thanks!
