### ISSUE TITLE
Surfaces have no colors

### ISSUE THREAD

**Issue by stla** [visjs/vis-graph3d#68]
Hello, 

 I have just installed `vis-graph3d.min.js` with `npm`. The surfaces have no colors, they are grey. This is the case for [this example](https://github.com/visjs/vis-graph3d/blob/master/examples/graph3d/16_styling_surface.html), whatever the colors configuration I choose.

**Comment by stla** [comment]
Weird, that works in Vivaldi, but not in Chrome.

**Comment by stla** [comment]
That also works in Firefox and Chromium, but not in Chrome. Maybe my Chrome version is outdated?

**Comment by stla** [comment]
Yeah, I've updated Chrome and this works now. Sorry.

**Comment by Thomaash** [comment]
Hi @stla,

can I just ask what version of Chrome was it? Because if it is one from the following list https://browserl.ist/?q=%3E+0.1%25+or+not+dead then it is a bug that should be addressed.

Thanks.

**Comment by stla** [comment]
@Thomaash 

It was Chrome 59 (was high time to update it).

I also have this issue in the RStudio browser. I wrapped `vis-graph3d` in a R package and the surfaces are grey in the RStudio viewer. But maybe my version of RStudio is too old.
