### ISSUE TITLE
Set/extend zoom limit options for zooming over points in the graph?

### ISSUE THREAD

**Issue by albertki** [visjs/vis-graph3d#8]
I know vis-network has methods and event properties to control zoom options. My graph is quite cluttered, and I'm wondering if features can be implemented to zoom more into points in the graph.

**Comment by mojoaxel** [comment]
@albertki Feel free to describe in more detail what options you would recommend.

_Also a little word of warning: We have no active maintainer for this repository at the moment. It is very unlikely that this will get implemented soon._ Maybe @wimrijnders wants to help?

**Comment by albertki** [comment]
Sure. More specifically, I currently have to plot several points in my scatter plot that are clustered together (their coordinates vary only by decimals in the hundredths). I would like to zoom in more so that I'm able to distinctly hover over each point and utilize the hover tooltips. I noticed there is a limit as to how much I can zoom in, and then it will not allow me to scroll any more. I was thinking t would be useful if this limit can be adjusted, or extended somehow is vis.js to accommodate greater zoom, if that is possible.
